spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
          hibernate:
          dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  datasource:
    url: jdbc:postgresql:///semantic_trajectory
    username: postgres
    password: postgres

  data:
    rest:
      basePath: /api

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  jmx:
    default_domain: semantic_trajectory_app
  application:
    name: semantic-trajectory

logging:
  level:
    org:
      springframework:
        web: debug
  file: /var/log/semantic_trajectory.log