spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql:///semantic_trajectory
    username: postgres
    password: postgres

  data:
    rest:
      basePath: /api

  jackson:
    deserialization:
      fail-on-unknown-properties: true